{
 "title": "New dashboard",
 "time": { "from": "2022-01-09T01:55:58.899Z", "to": "2022-03-06T01:00:49.139Z" },
 "panels": [
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns, \"timestamp\" FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, \"timestamp\" FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values, \"timestamp\" FROM metrics LIMIT 50 "
    }
   ]
  }
 ]
}